---
- hosts: localhost
  tasks:
  - name: Install Oracle JDK 8u201 from local source
    synchronize:
      src: ./jdk1.8.0_201
      dest: /lib/jvm/
  - name: Install latest mariadb service
    pacman:
      name: mariadb
      state: latest
      update_cache: yes
  - pause:
      seconds: 30
  - name: Enable mariadb service
    systemd:
      name: mariadb
      enabled: yes
      masked: no
  - name: Set JAVA_HOME variable in /etc/profile
    shell: echo "JAVA_HOME=/lib/jvm/jdk1.8.0_201" >> /etc/profile
  